# Global definition of compiler and its flags 

CWARNINGS5.2=-Wabi\
-Waggregate-return\
-Waggressive-loop-optimizations\
-Wall\
-Wattributes\
-Wbuiltin-macro-redefined\
-Wcast-align\
-Wcast-qual\
-Wconditionally-supported\
-Wconversion\
-Wconversion-null\
-Wcoverage-mismatch\
-Wcpp\
-Wctor-dtor-privacy\
-Wdate-time\
-Wdelete-incomplete\
-Wdeprecated\
-Wdeprecated-declarations\
-Wdisabled-optimization\
-Wdiv-by-zero\
-Wdouble-promotion\
-Weffc++\
-Wextra\
-Wfloat-equal\
-Wformat-signedness\
-Wfree-nonheap-object\
-Wimport\
-Winherited-variadic-ctor\
-Winline\
-Wint-to-pointer-cast\
-Winvalid-memory-model\
-Winvalid-offsetof\
-Winvalid-pch\
-Wliteral-suffix\
-Wlogical-op\
-Wmissing-declarations\
-Wmissing-include-dirs\
-Wmudflap\
-Wmultichar\
-Wnoexcept\
-Wnon-template-friend\
-Wodr\
-Wold-style-cast\
-Woverflow\
-Woverloaded-virtual\
-Wpacked\
-Wpacked-bitfield-compat\
-Wpadded\
-Wpedantic\
-Wpmf-conversions\
-Wpragmas\
-Wredundant-decls\
-Wreturn-local-addr\
-Wshadow\
-Wshift-count-negative\
-Wshift-count-overflow\
-Wsign-promo\
-Wsizeof-array-argument\
-Wstack-protector\
-Wstrict-aliasing\
-Wstrict-null-sentinel\
-Wstrict-overflow\
-Wsuggest-attribute=const\
-Wsuggest-attribute=format\
-Wsuggest-attribute=noreturn\
-Wsuggest-attribute=pure\
-Wsuggest-final-methods\
-Wsuggest-final-types\
-Wsuggest-override\
-Wswitch-bool\
-Wswitch-default\
-Wswitch-enum\
-Wsync-nand\
-Wsynth\
-Wsystem-headers\
-Wtrampolines\
-Wundef\
-Wunreachable-code\
-Wunsafe-loop-optimizations\
-Wunused-macros\
-Wunused-result\
-Wvarargs\
-Wvector-operation-performance\
-Wvirtual-move-assign\
-Wvla\
-Wwrite-strings\
-Wzero-as-null-pointer-constant

#-Wuseless-cast\
#-Wassign-intercept\
#-Wbad-function-cast\
#-Wc++-compat\
#-Wc90-c99-compat\
#-Wc99-c11-compat\
#-Wdeclaration-after-statement\
#-Wdesignated-init\
#-Wdiscarded-array-qualifiers\
#-Wdiscarded-qualifiers\
#-Wincompatible-pointer-types\
#-Wint-conversion\
# -Wjump-misses-init\
# -Wmissing-prototypes\
# -Wnested-externs\
# -Wold-style-definition\
# -Wpointer-to-int-cast\
# -Wproperty-assign-default\
# -Wprotocol\
# -Wselector\
# -Wstrict-prototypes\
# -Wstrict-selector-match\
# -Wtraditional\
# -Wtraditional-conversion\
# -Wundeclared-selector\
# -Wunsuffixed-float-constants\
 
# -fno-exceptions
# -fmax-errors=1

# CC = g++ -O0 -g -std=c++11 -pedantic -Wall -Wextra -Wno-unused-variable -Wno-sign-compare -Wno-missing-braces -Wmissing-field-initializers -Werror=implicit
# CC = clang++ -O0 -g -std=c++11 -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -pedantic -Wall -Wextra -Wno-unused-variable -Wno-sign-compare -Wno-missing-braces -Wmissing-field-initializers -Werror=implicit
CC = g++ -O0 -g -fsanitize=leak -std=c++1z -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -pedantic -Wall -Wextra -Wno-unused-variable -Wno-sign-compare -Wno-missing-braces -Wmissing-field-initializers -Werror=implicit

# -D_GLIBCXX_DEBUG

