

tests.basic: 
	for i in ./basic/*.out; do (./$$i > /dev/null) || break; done

tests.combinatorics: 
	for i in ./combinatorics/*.out; do (./$$i > /dev/null) || break; done

tests.operators: 
	for i in ./operators/*.out; do (./$$i > /dev/null) || break; done

tests.dense: 
	for i in ./dense/*.out; do (./$$i > /dev/null) || break; done

tests.sparse: 
	for i in ./sparse/*.out; do (./$$i > /dev/null) || break; done

tests.solver: 
	for i in ./solver/*.out; do (./$$i > /dev/null) || break; done

tests.mesh: 
	for i in ./mesh/*.out; do (./$$i > /dev/null) || break; done

tests.vtk: 
	for i in ./vtk/*.out; do (./$$i > /dev/null) || break; done


tests:
	make tests.combinatorics tests.operators tests.dense tests.sparse tests.solver
