affix.basic         := basic
affix.utility       := utility basic
affix.combinatorics := combinatorics basic
affix.operators     := operators combinatorics utility basic
affix.dense         := dense sparse operators combinatorics utility basic
affix.sparse        := sparse dense operators combinatorics utility basic
affix.solver        := solver sparse dense operators combinatorics utility basic
affix.mesh          := mesh dense sparse operators combinatorics utility basic
affix.vtk           := vtk $(affix.mesh)
#affix.matrixmarket  := matrixmarket
affix.fem           := fem mesh solver dense sparse operators combinatorics utility basic 
affix.solverfem     := fem mesh solver dense sparse operators combinatorics utility basic 
affix.sullivan2D    := fem vtk mesh solver dense sparse operators combinatorics utility basic 
affix.sullivan3D    := fem vtk mesh solver dense sparse operators combinatorics utility basic 
affix.whitney2D     := fem vtk mesh solver dense sparse operators combinatorics utility basic 
affix.whitney3D     := fem vtk mesh solver dense sparse operators combinatorics utility basic 
affix.nullspace     := fem vtk mesh solver dense sparse operators combinatorics utility basic 
affix.afem          := fem vtk mesh solver dense sparse operators combinatorics utility basic 
# TODO: Descending order for these lists ...
