affix.basic         := basic
affix.utility       := utility basic
affix.combinatorics := combinatorics basic
affix.operators     := operators combinatorics basic
affix.dense         := dense sparse operators combinatorics basic
affix.sparse        := sparse dense operators combinatorics basic
affix.solver        := solver sparse dense operators combinatorics basic
affix.mesh          := mesh dense sparse operators combinatorics basic
affix.vtk           := vtk $(affix.mesh)
#affix.matrixmarket  := matrixmarket
affix.fem           := fem vtk mesh solver dense sparse operators combinatorics basic
affix.solverfem     := fem vtk mesh solver dense sparse operators combinatorics basic 
affix.sullivan2D    := fem vtk mesh solver dense sparse operators combinatorics basic 
affix.sullivan3D    := fem vtk mesh solver dense sparse operators combinatorics basic 
affix.whitney2D     := fem vtk mesh solver dense sparse operators combinatorics basic 
affix.whitney3D     := fem vtk mesh solver dense sparse operators combinatorics basic 
affix.nullspace     := fem vtk mesh solver dense sparse operators combinatorics basic 
affix.afem          := fem vtk mesh solver dense sparse operators combinatorics basic 
# TODO: Descending order for these lists ...
