#include "global.diffmatrix.cpp"
#include "global.massmatrix.cpp"
#include "indexfunctions.cpp"
#include "local.polynomialmassmatrix.cpp"
#include "global.elevation.cpp"
#include "global.sullivanincl.cpp"
#include "lagrangematrices.cpp"
#include "utilities.cpp"