name: C/C++ CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: build project
      run: make
#    - name: make cpplint
#      run: make cpplint
