name: Compile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1-5'
  
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    timeout-minutes: 30

    steps:

    - name: Show Processor Information (Linux)
      run: lscpu

    - name: print software versions
      run: g++ --version; clang++ --version; clang-tidy --version;
    
    - name: Install OpenMP
      run: sudo apt-get install -y libomp-dev
    
    - name: checkout repository
      uses: actions/checkout@v4
    
    - name: check header and source files 
      run: make checkheaders && make checksources
#    - name: static code analysis clang-tidy
#      run: make tidy
    
    - name: build project
      run: make all
