name: C/C++ CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest 
    
    timeout-minutes: 30

    steps:
    - name: print software versions
      run: clang++ --version; g++ --version; clang-tidy --version 
    - name: checkout repository
      uses: actions/checkout@v3
    - name: static code analysis check header files
      run: make checkheaders
#    - name: static code analysis clang-tidy
#      run: make tidy
    - name: build project
      run: make all
