name: Unit tests (1)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * MON'
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    timeout-minutes: 120

    steps:
#    - name: install valgrind here 
#      run: sudo apt install -y valgrind
    - name: Install OpenMP
      run: sudo apt-get install -y libomp-dev
    - name: Show Processor Information (Linux)
      run: lscpu
    - name: print software versions
      run: g++ --version; clang++ --version; clang-tidy --version;
    - name: checkout repository...
      uses: actions/checkout@v4
    - name: build project...
      run: make
    - name: run tests (base)...
      run: cd tests/ && make base.run && cd .. 
#      continue-on-error: true
    - name: run tests (utility)...
      run: cd tests/ && make utility.run && cd .. 
#      continue-on-error: true
    - name: run tests (combinatorics)...
      run: cd tests/ && make combinatorics.run && cd .. 
#      continue-on-error: true
    - name: run tests (operators)...
      run: cd tests/ && make operators.run && cd .. 
#      continue-on-error: true
    - name: run tests (dense)...
      run: cd tests/ && make dense.run && cd .. 
#      continue-on-error: true
    - name: run tests (sparse)...
      run: cd tests/ && make sparse.run && cd .. 
#      continue-on-error: true
    - name: run tests (solver)...
      run: cd tests/ && make solver.run && cd .. 
#      continue-on-error: true
    - name: run tests (mesh)...
      run: cd tests/ && make mesh.run && cd .. 
#      continue-on-error: true
    - name: run tests (vtk)...
      run: cd tests/ && make vtk.run && cd .. 
#      continue-on-error: true
    - name: run tests (fem)...
      run: cd tests/ && make fem.run && cd .. 
#      continue-on-error: true
    - name: run tests (image)...
      run: cd tests/ && make image.run && cd .. 
#      continue-on-error: true
