name: Unit tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * SUN'
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    timeout-minutes: 60

    steps:
#    - name: install valgrind here 
#      run: sudo apt install -y valgrind
    - name: checkout repository...
      uses: actions/checkout@v2
    - name: build project...
      run: make
    - name: run tests (basic)...
      run: cd tests/ && make basic.run && cd .. 
    - name: run tests (utility)...
      run: cd tests/ && make utility.run && cd .. 
    - name: run tests (combinatorics)...
      run: cd tests/ && make combinatorics.run && cd .. 
    - name: run tests (operators)...
      run: cd tests/ && make operators.run && cd .. 
    - name: run tests (dense)...
      run: cd tests/ && make dense.run && cd .. 
    - name: run tests (sparse)...
      run: cd tests/ && make sparse.run && cd .. 
    - name: run tests (solver)...
      run: cd tests/ && make solver.run && cd .. 
    - name: run tests (mesh)...
      run: cd tests/ && make mesh.run && cd .. 
    - name: run tests (vtk)...
      run: cd tests/ && make vtk.run && cd .. 
    - name: run tests (fem)...
      run: cd tests/ && make fem.run && cd .. 
#   - name: run tests (solverfem)...
#     run: cd tests/ && make solverfem.run && cd .. 
#     - name: run tests (sullivan2D)...
#       run: cd tests/ && make sullivan2D.run && cd .. 
#     - name: run tests (sullivan3D)...
#       run: cd tests/ && make sullivan3D.run && cd ..  
#     - name: run tests (sullivan2D)...
#       run: cd tests/ && make whitney2D.run && cd .. 
#     - name: run tests (sullivan3D)...
#       run: cd tests/ && make whitney3D.run && cd .. 
