name: Unit tests

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 * * * *'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository...
      uses: actions/checkout@v2
    - name: build project...
      run: make
    - name: run tests (basic)...
      run: cd tests/ && make basic.run && cd .. 
    - name: run tests (utility)...
      run: cd tests/ && make utility.run && cd .. 
    - name: run tests (combinatorics)...
      run: cd tests/ && make combinatorics.run && cd .. 
    - name: run tests (operators)...
      run: cd tests/ && make operators.run && cd .. 
    - name: run tests (dense)...
      run: cd tests/ && make dense.run && cd .. 
    - name: run tests (sparse)...
      run: cd tests/ && make sparse.run && cd .. 
    - name: run tests (solver)...
      run: cd tests/ && make solver.run && cd .. 
#    - name: run tests (mesh)...
#      run: cd tests/ && make mesh.run && cd .. 
#    - name: run tests (vtk)...
#      run: cd tests/ && make vtk.run && cd .. 
#    - name: run tests (fem)...
#      run: cd tests/ && make fem.run && cd .. 
#    - name: run tests (experiments)...
#      run: cd tests/ && make experiments.run && cd .. 
