name: Unit tests (3)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * MON'
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    timeout-minutes: 600

    steps:
#    - name: install valgrind here 
#      run: sudo apt install -y valgrind
    - name: Install OpenMP
      run: sudo apt-get install -y libomp-dev
    - name: Show Processor Information (Linux)
      run: lscpu
    - name: print software versions
      run: g++ --version; clang++ --version; clang-tidy --version;
    - name: checkout repository...
      uses: actions/checkout@v4
    - name: build project...
      run: make OPTIMIZED_DEBUG=yes
    - name: run tests (sullivan3D)...
      run: cd tests/ && make sullivan3D.run && cd ..
#       continue-on-error: true
    - name: run tests (whitney3D)...
      run: cd tests/ && make whitney3D.run && cd ..
#       continue-on-error: true
    - name: run tests (nullspace)...
      run: cd tests/ && make nullspace.run && cd ..
#       continue-on-error: true
#     - name: run tests (eigenvalue)...
#       run: cd tests/ && make eigenvalue.run && cd ..
# #       continue-on-error: true
#     - name: run tests (afem)...
#       run: cd tests/ && make afem.run && cd ..
# #       continue-on-error: true
